// Real previous-year questions transcribed from actual AP AEE Electrical
// Engineering papers (image scans). The papers carry no answer key, so each
// answer here was worked out and only questions with a confident answer are
// included; ambiguous or partially-scanned items are omitted.
//
// Source: EEA/502 — Electrical Engineering, Paper II (2012).

export const PAPER_SUBJECTS = [
  { id: 'pyq2012p2', name: 'PYQ 2012 · Paper II', icon: '📄', group: 'papers' },
]

export const PAPER_GROUPS = {
  papers: 'Previous Year Papers',
}

export const PAPER_QUESTIONS = [
  { id: 'p2_1', subject: 'pyq2012p2', q: 'The essential condition for parallel operation of two DC generators is that they have the same:', options: ['kW rating', 'Terminal voltage', 'Operating speed', 'All of these'], answer: 1, explanation: 'DC generators to be paralleled must have the same terminal voltage (and same polarity).' },
  { id: 'p2_2', subject: 'pyq2012p2', q: 'A DC motor delivering constant power output initially operates at 1500 rpm with a torque of 200 Nm. The torque delivered at 1200 rpm is:', options: ['160 Nm', '200 Nm', '230 Nm', '250 Nm'], answer: 3, explanation: 'Constant power P = Tω ⇒ T₂ = T₁·N₁/N₂ = 200×1500/1200 = 250 Nm.' },
  { id: 'p2_3', subject: 'pyq2012p2', q: 'The developed torque (Td) vs armature current (Ia) characteristic of a DC series motor is:', options: ['Straight line throughout', 'Parabola throughout', 'Straight line up to a certain load, then parabola', 'Parabola up to a certain load, then straight line'], answer: 3, explanation: 'Before saturation φ∝Ia so T∝Ia² (parabola); after saturation φ is constant so T∝Ia (straight line).' },
  { id: 'p2_5', subject: 'pyq2012p2', q: 'If the current flowing in a lamp drops by 1 percent, the power will decrease by approximately:', options: ['2%', '4%', '0.1%', '1%'], answer: 0, explanation: 'P = I²R ⇒ ΔP/P ≈ 2·ΔI/I = 2×1% = 2%.' },
  { id: 'p2_6', subject: 'pyq2012p2', q: 'The most suitable material for a transformer core is:', options: ['Hot rolled grain oriented steel', 'Cold rolled grain oriented steel', 'Aluminium', 'Copper'], answer: 1, explanation: 'CRGO (cold rolled grain oriented) silicon steel gives low core loss.' },
  { id: 'p2_8', subject: 'pyq2012p2', q: 'The thickness of stator laminations is of the order of:', options: ['0.5 mm', '1 mm', '0.05 mm', 'None of these'], answer: 0, explanation: 'Laminations are typically about 0.35–0.5 mm thick to limit eddy-current loss.' },
  { id: 'p2_10', subject: 'pyq2012p2', q: 'The current in an R-L circuit is i = Iₘ sin ωt. The expression for the applied voltage is:', options: ['v = Vₘ sin(ωt + φ)', 'v = Vₘ sin(ωt − φ)', 'v = Vₘ sin ωt', 'v = Vₘ sin(ωt − π/2)'], answer: 0, explanation: 'In an inductive circuit voltage leads current by φ, so v = Vₘ sin(ωt + φ).' },
  { id: 'p2_12', subject: 'pyq2012p2', q: 'For speed ratios other than 2:1, the speed of an induction motor can be controlled by varying the number of stator poles using:', options: ['Multiple stator winding', 'Pole amplitude modulation technique', 'Consequent pole technique', 'Any of these'], answer: 1, explanation: 'Pole amplitude modulation (PAM) gives pole ratios other than the fixed 2:1 of the consequent-pole method.' },
  { id: 'p2_13', subject: 'pyq2012p2', q: 'In 3-phase induction motors, speeds higher than synchronous speed can be obtained by:', options: ['Line voltage control', 'Rotor slip power control', 'Rotor resistance control', 'Frequency control'], answer: 1, explanation: 'Slip-power recovery (Scherbius) schemes allow super-synchronous speeds.' },
  { id: 'p2_14', subject: 'pyq2012p2', q: 'The method of speed control used to run a DC shunt motor above its rated speed is:', options: ['Armature resistance control', 'Field control', 'Armature voltage control', 'Series-parallel control'], answer: 1, explanation: 'Field weakening (field control) raises speed above rated (base) speed.' },
  { id: 'p2_16', subject: 'pyq2012p2', q: 'With total secondary resistance R and reactance X, secondary current I₂ and a leading pf cosφ₂, the rise in voltage when load is thrown off is:', options: ['I₂R cosφ₂ − I₂X sinφ₂', 'I₂R cosφ₂ + I₂X sinφ₂', 'I₂R sinφ₂ − I₂X cosφ₂', 'I₂R sinφ₂ + I₂X cosφ₂'], answer: 0, explanation: 'For a leading pf the regulation term is (I R cosφ − I X sinφ), giving a voltage rise.' },
  { id: 'p2_18', subject: 'pyq2012p2', q: 'In a Scott-connected transformer, the number of turns in the main and teaser transformers respectively are:', options: ['T and √3·T/2', 'T/2+T/2 and √3·T/2', 'T/2+T/2 and 2T/√3', 'T/2 and √3·T/2'], answer: 0, explanation: 'The teaser is tapped at 0.866 (=√3/2) of the main winding turns T.' },
  { id: 'p2_19', subject: 'pyq2012p2', q: 'The purpose of interpoles in DC machines is to nullify:', options: ['The demagnetizing effect of armature mmf', 'The cross-magnetizing effect of armature mmf', 'The reactance voltage', 'Both the cross-magnetizing mmf and the reactance voltage'], answer: 3, explanation: 'Interpoles neutralise the reactance voltage (aiding commutation) and the cross-magnetising armature mmf in the interpolar zone.' },
  { id: 'p2_22', subject: 'pyq2012p2', q: 'In a CRO, the quantity to be measured is applied across the:', options: ['Focusing electrodes', 'Cathode', 'Y-plates', 'X-plates'], answer: 2, explanation: 'The signal is applied to the vertical (Y) deflection plates.' },
  { id: 'p2_23', subject: 'pyq2012p2', q: 'A wire has resistance 2 Ω. If its diameter is reduced to half (same length), the resistance becomes:', options: ['1 Ω', '4 Ω', '0.5 Ω', '8 Ω'], answer: 3, explanation: 'R = ρl/A and A ∝ d². Half diameter ⇒ A becomes 1/4 ⇒ R becomes 4× = 8 Ω.' },
  { id: 'p2_24', subject: 'pyq2012p2', q: 'In electric discharge lamps, light is produced by:', options: ['Cathode ray emission', 'Ionization in a gas or vapour', 'Heating effect of current', 'Magnetic effect of current'], answer: 1, explanation: 'Discharge lamps emit light from ionised gas/vapour.' },
  { id: 'p2_25', subject: 'pyq2012p2', q: 'Which of the following bulbs operates on the least power?', options: ['GLS bulb', 'Torch bulb', 'Neon bulb', 'Night bulb'], answer: 2, explanation: 'Indicator neon bulbs draw only a fraction of a watt.' },
  { id: 'p2_26', subject: 'pyq2012p2', q: 'The gas used in a sodium vapour lamp is:', options: ['Argon', 'Neon', 'Nitrogen', 'Oxygen'], answer: 1, explanation: 'Neon is used (with sodium) to start the discharge, giving the initial red glow.' },
  { id: 'p2_28', subject: 'pyq2012p2', q: 'A synchronous generator on a grid bus-bar is to be made to operate as a motor. This is done when the:', options: ['Direction of rotation is reversed', 'Phase sequence is changed', 'Field excitation is decreased', 'Mechanical input is made less than the shaft losses'], answer: 3, explanation: 'When mechanical input falls below the losses, the machine draws electrical power and motors.' },
  { id: 'p2_29', subject: 'pyq2012p2', q: 'The speed of a synchronous motor depends upon:', options: ['Supply voltage', 'Supply frequency', 'Number of poles', 'Both supply frequency and number of poles'], answer: 3, explanation: 'Ns = 120 f / P, so it depends on both frequency and pole number.' },
  { id: 'p2_30', subject: 'pyq2012p2', q: 'A series R-L circuit has R = 1 Ω, L = 1 H and current i = sin t. The total applied voltage V is:', options: ['2 sin t', '2 cos t', 'sin(t + 45°)', '√2 sin(t + 45°)'], answer: 3, explanation: 'V_R = sin t, V_L = L di/dt = cos t; sum = √2 sin(t + 45°).' },
  { id: 'p2_32', subject: 'pyq2012p2', q: 'Two DC series motors in series draw current I and run at speed N. When connected in parallel taking the same current I from the supply, the speed of each motor is:', options: ['N', '2N', '4N', 'N/2'], answer: 2, explanation: 'Series: each has V/2, current I. Parallel: each has V, current I/2 (so half flux). Working through Eb=kφN gives 4N.' },
  { id: 'p2_33', subject: 'pyq2012p2', q: 'The purpose of providing dummy coils in a DC machine armature is to:', options: ['Reduce eddy currents', 'Increase induced voltage', 'Decrease armature resistance', 'Provide mechanical balance'], answer: 3, explanation: 'Dummy (idle) coils only fill empty slots to mechanically balance the armature.' },
  { id: 'p2_34', subject: 'pyq2012p2', q: 'A current source I·u(t) feeds L and R in parallel. The voltage v(t) across R for t > 0 is:', options: ['IR·e^(−Lt/R)', 'IR·e^(−Rt/L)', 'IR(1 − e^(−Rt/L))', 'IR(1 − e^(−Lt/R))'], answer: 1, explanation: 'At t=0⁺ the inductor is open so v=IR; it decays with τ = L/R: v = IR·e^(−Rt/L).' },
  { id: 'p2_36', subject: 'pyq2012p2', q: 'The most efficient electrical machine is the:', options: ['DC machine', 'Induction motor', 'Synchronous machine', 'Transformer'], answer: 3, explanation: 'Being static with no rotational losses, a transformer has the highest efficiency.' },
  { id: 'p2_37', subject: 'pyq2012p2', q: 'Oil in a transformer is used for:', options: ['Insulation', 'Insulation and cooling', 'Lubrication', 'Insulation, cooling and lubrication'], answer: 1, explanation: 'Transformer oil provides both insulation and cooling (no moving parts to lubricate).' },
  { id: 'p2_41', subject: 'pyq2012p2', q: 'Carbon arc lamps are commonly used in:', options: ['Photography', 'Cinema projectors', 'Domestic lighting', 'Street lighting'], answer: 1, explanation: 'Their high-intensity light suited cinema (film) projectors.' },
  { id: 'p2_42', subject: 'pyq2012p2', q: 'A shaded-pole induction motor does NOT have the advantage of:', options: ['High starting torque', 'Rugged construction', 'Low initial and maintenance cost', 'Comparatively small starting current'], answer: 0, explanation: 'Shaded-pole motors have very low starting torque — that is not one of their advantages.' },
  { id: 'p2_43', subject: 'pyq2012p2', q: 'Which of the following needs the lowest level of illumination?', options: ['Auditoriums', 'Railway platforms', 'Displays', 'Fine engravings'], answer: 1, explanation: 'Railway platforms need only low illumination; fine engraving work needs the highest.' },
  { id: 'p2_44', subject: 'pyq2012p2', q: 'The distance between two coil sides connected to the same commutator segment is called the:', options: ['Winding pitch', 'Back pitch', 'Front pitch', 'Full pitch'], answer: 2, explanation: 'The front pitch is the distance between coil sides joined at the same commutator segment.' },
]
